language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  # PyPy versions
  - "pypy"
  - "pypy3" # Pypy3 2.4.0
  - "pypy-5.3.1"
# command to run tests
script:
  - pushd tests >/dev/null && ./runtests.sh && popd >/dev/null
